loki:
  enabled: true
  nameOverride: "loki"
  fullnameOverride: "loki"
  replicaCount: 1
  image:
    repository: grafana/loki
    tag: 2.6.1
  service:
    type: NodePort
    port: 3100
  persistence:
    enabled: true
    pvs:
      - name: loki-chunks-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/chunks
      - name: loki-index-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/index
      - name: loki-cache-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/cache
    pvcs:
      - name: loki-chunks-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
        mountPath: /var/loki/chunks
      - name: loki-index-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
        mountPath: /var/loki/index
      - name: loki-cache-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
        mountPath: /var/loki/cache

  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem

      filesystem:
        directory: /var/loki/chunks

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h # 30 days

promtail:
  enabled: true
  nameOverride: "promtail"
  fullnameOverride: "promtail"
  debug: true
  persistence:
    enabled: true
    pvName: promtail-pv
    pvcName: promtail-pvc
    storageClassName: longhorn
    storage: 1Gi
    accessModes:
      - ReadWriteOnce
    reclaimPolicy: Retain
    path: /data/promtail
    volumeMode: Filesystem

  config:
    enabled: true
    logLevel: info
    logFormat: logfmt
    serverPort: 3101

    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      - job_name: kubernetes
        pipeline_stages:
          - json:
              expressions:
                log: log
                level: level

          - match:
              selector: '{level=~"(?i)info|(?i)warn"}'
              stages:
                - drop: {}

          - match:
              selector: '{level=~"(?i)debug"}'
              stages:
                - drop: {}

          - match:
              selector: '{level=~"(?i)error"}'
              stages:
                - drop: {}
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_container_name]
            target_label: container
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container_name
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
            replacement: $1

        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes
              __path__: /var/log/pods/*/*.log

grafana:
  enabled: true
  nameOverride: "grafana"
  fullnameOverride: "grafana"
  adminPassword: "admin"
  service:
    type: NodePort
    port: 3000
