loki:
  persistence:
    enabled: true
    pvs:
      - name: loki-chunks-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/chunks
      - name: loki-index-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/index
      - name: loki-cache-pv
        storageClassName: longhorn
        storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        reclaimPolicy: Retain
        path: /var/loki/cache
    pvcs:
      - name: loki-chunks-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
      - name: loki-index-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi
      - name: loki-cache-pvc
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        storage: 5Gi

  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: filesystem

      filesystem:
        directory: /var/loki/chunks

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h # 30 days

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /var/log/promtail/positions.yaml # Note: This will be an ephemeral location (in-memory storage)
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: .+
        pipeline_stages:
          - docker: {}
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/pods/*/*.log

grafana:
  enabled: true
  adminPassword: "admin"
  service:
    type: NodePort
    port: 3000
