{{- if .Values.loki.persistence.enabled }}
{{- range .Values.loki.persistence.pvs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Release.Name }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .storage }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
  hostPath:
    path: {{ .path }}
---
{{- end }}
{{- end }}
