{{- if .Values.loki.persistence.enabled }}
{{- range .Values.loki.persistence.pvcs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .storage }}
---
{{- end }}
{{- end }}

