apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-chunks-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/loki/chunks
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-index-pv
spec:
  storageClassName: longhorn
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/loki/index
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-cache-pv
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/loki/cache
